### ISSUE TITLE
Session tracker

### ISSUE THREAD

**Issue by tomzx** [tomzx/loot-tracker#3]
- [x] Start/Pause a session
- [x] Reset/Start a new a session
- [ ] Multiple session tracking (play session, dungeon instance, manually started sessions)

**Comment by tomzx** [comment]
Mostly done @ 051b285d62c24d40b7cd679ddbc6c6c5b78e2e72. Only left is the various session tracking behaviors (per session, instance, character, etc.).
